# Generated by Django 3.2.9 on 2021-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racksuser',
            name='bitnob_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='btc_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='btc_balance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='naira_balance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='type_of_account',
            field=models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal')], max_length=255),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='btc_amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='reference',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
