# Generated by Django 3.2.9 on 2021-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racksuser',
            name='btc_balance',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='naira_balance',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='btc_amount',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
