# Generated by Django 3.2.9 on 2021-11-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211123_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racksuser',
            name='btc_balance',
            field=models.DecimalField(decimal_places=10, default=0.3, max_digits=15),
            preserve_default=False,
        ),
    ]
