# Generated by Django 3.2.9 on 2021-11-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_racksuser_btc_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racksuser',
            name='naira_balance',
            field=models.DecimalField(decimal_places=10, default=0.2, max_digits=15),
            preserve_default=False,
        ),
    ]
