# Generated by Django 3.2.9 on 2021-11-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_racksuser_naira_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racksuser',
            name='btc_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='racksuser',
            name='naira_balance',
            field=models.FloatField(null=True),
        ),
    ]
